# Generated by Django 3.1.13 on 2024-05-16 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('numero_dossier', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('localisation', models.CharField(max_length=50)),
                ('numer_boite', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Archive',
            },
        ),
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id_boite', models.AutoField(db_column='id_boite', primary_key=True, serialize=False)),
                ('mention', models.CharField(max_length=150)),
                ('numero_rang', models.CharField(default='Aucune', max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('etat', models.IntegerField(default=1)),
                ('harmoire', models.CharField(default='Aucune', max_length=150)),
                ('numero_comp', models.CharField(default='Aucune', max_length=50)),
                ('niveau', models.CharField(default='Aucune', max_length=50)),
                ('id_user', models.IntegerField(db_column='id_user')),
            ],
            options={
                'db_table': 'Boite',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_dmd', models.AutoField(db_column='id_dmd', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('commentaire', models.CharField(max_length=255)),
                ('date_dmd', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(null=True)),
                ('id_demandeur', models.IntegerField(db_column='id_demandeur')),
                ('id_accepteur', models.IntegerField(db_column='id_acepteur')),
                ('etat', models.IntegerField(default=0)),
                ('id_docuement', models.IntegerField(db_column='id_document')),
                ('id_boite', models.IntegerField(db_column='id_boite')),
            ],
            options={
                'db_table': 'Demande',
            },
        ),
        migrations.CreateModel(
            name='DetailsDossier',
            fields=[
                ('id_dossier', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('numero_bl', models.CharField(max_length=15)),
                ('eta', models.CharField(max_length=15)),
                ('nom_navire', models.CharField(max_length=50)),
                ('numero_voyage', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=50)),
                ('numer_boite', models.CharField(max_length=50)),
                ('carton', models.CharField(max_length=50)),
                ('classeur', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Details_dossier',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(db_column='id_document', primary_key=True, serialize=False)),
                ('numero_docuemnt', models.CharField(max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_destruction', models.DateField(null=True)),
                ('chemin_acces', models.CharField(max_length=150)),
                ('disponibilite', models.IntegerField(default=0)),
                ('numero_bl', models.CharField(max_length=15)),
                ('eta', models.CharField(max_length=10)),
                ('client', models.CharField(max_length=40)),
                ('nom_navire', models.CharField(max_length=100)),
                ('numero_voyage', models.CharField(max_length=100)),
                ('id_us', models.IntegerField(db_column='id_us')),
                ('id_boite', models.IntegerField(db_column='id_boite')),
                ('id_per', models.IntegerField(db_column='id_per')),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id_harmoire', models.CharField(max_length=150)),
                ('numero_comp', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('numero_dossier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_user', models.IntegerField(db_column='id_user')),
            ],
            options={
                'db_table': 'Localisation',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_permission', models.AutoField(db_column='id_per', primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('id_user', models.IntegerField(db_column='id_us')),
            ],
            options={
                'db_table': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_utilisateur', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('direction', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('Facturation', 'Facturation'), ('Comptabilité', 'Comptabilite'), ('Exploitation', 'Exploitatain'), ('Documentation', 'Documentation')], max_length=50)),
                ('privelege', models.CharField(choices=[('Ajouter', 'Ajouter'), ('Modifier', 'Modifier'), ('Supprimer', 'Supprimer'), ('Consulter', 'Consulter')], max_length=50)),
                ('nom_acces', models.CharField(max_length=255)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Permissionn',
            },
        ),
    ]
